Only initialize pygame.mixer if necessary
Currently, pygame.mixer.init() is always called if it's installed -
even if the user doesn't need or want it.

If have pygame installed and you configured your audio setup in a way
that pygame fails to detect properly, this even produces an error, even
if you do not intent to use pygame:
  error: No available audio device

This commit moves the pygame.mixer.init() call into the speak() method,
which is the only location where pygame is actually used. To avoid
multiple pygame.mixer.init()-calls, we test if pygame.mixer has already
been initialized via pygame.mixer.get_init().